### ISSUE TITLE
Rewrite to use workspace-d instead

### ISSUE THREAD

**Issue by Vild** [Pure-D/atomize-d#28]
Rewriting the plugin to use [workspace-d](https://github.com/Pure-D/workspace-d) would mean that it will receive features faster and would be functionally equal to [code-d](https://github.com/Pure-D/code-d) for VSCode.

Would fix most issues. For example #19, #1, #20

**Comment by WebFreak001** [comment]
github pls, assume both @WebFreak001 and @Vild are assigned

**Comment by MggMuggins** [comment]
How far along is this re-write? I'm interested in helping out.

**Comment by WebFreak001** [comment]
@MggMuggins I made the initial port of atomize-d which basically works already. Things that can be done to finish it now:
* dependency installer (see code-d)
* update workspace-d.ts again (just copy it from code-d and fix all dependencies using vscode to use proper interfaces for the atom packages)
* dml auto complete (see code-d)
* dub linting (commented dub build function), might be the easiest feature to start with because it's just adding another linter
* goto definition
* documentation lookup (hover)
* document outline
* workspace symbol search

Most of the features aren't implemented because there is no standard API for making those and when I wrote the code nobody bothered to even try to make such an API either. I can imagine that now there might be APIs or extra plugins for these features we can depend on that other plugins use as well. So the first step to do right now would be doing some research to find out what other plugins are using as APIs and how we can use them too. The thing we want the least is a lot of different panels and keybindings from different plugins clashing for priority.
