### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by aberba** [Pure-D/atomize-d#32]
Is working on this?

**Comment by WebFreak001** [comment]
currently not really, the code is mostly shared with code-d though and can be ported easily for most things because the base is already there. I will work on it some time eventually, just not today. When the time is right and I feel like working on this.

**Comment by MggMuggins** [comment]
I'd like to see an actively maintained D atom package. I like d-struct's syntax scheme, but this seems to have more functionality, although it's not really production-grade...

**Comment by aminya** [comment]
@WebFreak001 I am interested to maintain this package and make it up to date with the vscode extension. Can I get an invitation to become a member?

**Comment by WebFreak001** [comment]
@aminya hi, cool thanks for the interest. I can't really recall too much activity on the D community from you yet, plus there aren't a lot of D repositories on your account so I wouldn't add you as member just yet.

However you can fork this repository and work on features and PR all of them. As there isn't any activity on this repo anyway I will just do some very basic reviews and give you tips if you want, but would otherwise just merge your PRs.

**Comment by aminya** [comment]
@WebFreak001 

>  I can't really recall too much activity on the D community from you yet, plus there aren't a lot of D repositories on your account so I wouldn't add you as member just yet.

I have become interested in D recently, and I don't have many D projects yet, but I am the owner of @atom-community. 

> However you can fork this repository and work on features and PR all of them. As there isn't any activity on this repo anyway I will just do some very basic reviews and give you tips if you want, but would otherwise just merge your PRs.

Yes. We can start with that.
